services:
  mysql:
    image: mysql:8.4
    container_name: stockmate-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: stockmate
      MYSQL_USER: stockmate
      MYSQL_PASSWORD: stockmate1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: